name: Parse List

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'packs/**'
      - 'index.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.8.0'

      - name: Install dependencies
        run: npm install

      - name: Parse list
        run: node index.js packs

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions